### ISSUE TITLE
Is this an issue? [task2.3 server floating point exception]

### ISSUE THREAD

**Issue by ggulesir** [m4n1c22/OS2_Lab#13]
![screenshot at 2016-05-12 12 43 11](https://cloud.githubusercontent.com/assets/8045250/15212075/1d74bd4e-183f-11e6-9665-c61623559ccf.png)
![screenshot at 2016-05-12 12 42 49](https://cloud.githubusercontent.com/assets/8045250/15212076/1ea8127e-183f-11e6-9f7d-df59f6a58b0b.png)

I am not sure whether this is a problem. I have latest version, I created requests directory under task2 folder. I ran following commands without any additional option:

Terminal 1:  make comp_client_task2_3 
                   make client_exec_task2_3

Terminal 2: make comp_server_task2_3
                   make server_exec_task2_3

During execution I terminate client.Seems everything ok but at the end server gives floating point exception.

Another case without even running client, server runs and at the end again same exception happens.

**Comment by m4n1c22** [comment]
Minor exception handling issue. There was declaration inside readRequest() `int failure_rate=100/failure_chance` I had written it outside the exception handling part. Due to which whenever there is a Division by zero exception it will fail.

[This commit](https://github.com/m4n1c22/OS2_Lab/commit/5e1b799d5d6517d201062487137f1a280e3eb2e8) fixes the bug.
